# Generated by Django 2.1.7 on 2019-03-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190316_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_category',
            new_name='book_categories',
        ),
    ]
